### ISSUE TITLE
No way to cancel "New firm"

### ISSUE THREAD

**Issue by nickom** [sunlightlabs/hanuman#2]
If you click the "New firm" button there's no way to cancel and return to work on the firm you're viewing.

Options when you hit "New firm":
![screen shot 2015-05-19 at 5 46 37 pm](https://cloud.githubusercontent.com/assets/3171982/7714732/165fc8b0-fe4f-11e4-9ead-c411378723a6.png)

**Comment by apendleton** [comment]
Okay, so the complicating factor here is whether or not they've already gone through another dialog. If you at any point on this firm have saved any bio pages, when you try to leave the firm you're first presented with the dialog to confirm which pages are bio pages or not, and then after you hit save, you get this dialog. If you haven't, you go straight to this dialog.

If it's the former case, we can't really go back, otherwise we risk allowing the user to save multiple, conflicting versions of which pages are or are not bio pages, since they'd get an opportunity to submit those again when they tried to leave again...

Fortunately, though, the bio-vs-non-bio dialog has a cancel button already. So, the compromise that will go up in the next release: there's a cancel button in whichever dialog you see first. If it's this one, it has a cancel button, but if it's the view log confirmation, you see a cancel button in that dialog but not this one.
